unit_tests: &unit_tests
  steps:
    - checkout
    - restore_cache:
        key: dependency-cache-{{ checksum "package-lock.json" }}
    - run:
        name: Install Latest NPM.
        command: npm i -g npm@latest
    - run:
        name: NPM Install.
        command: npm i
    - run:
        name: Run unit tests.
        command: npm run ci:test
canary_tests: &canary_tests
  steps:
    - checkout
    - restore_cache:
        key: dependency-cache-{{ checksum "package-lock.json" }}
    - run:
        name: Install Latest NPM.
        command: npm i -g npm@latest
    - run:
        name: NPM Install.
        command: npm i
    - run:
        name: Install Webpack Canary.
        command: npm i --no-save webpack@next
    - run:
        name: Run unit tests.
        command: if [[ $(compver --name webpack --gte next --lt latest) < 1 ]] ; then printf "Next is older than Latest - Skipping Canary Suite"; else npm run ci:test ; fi

version: 2
jobs:
  dependency_cache:
    docker:
      - image: webpackcontrib/circleci-node-base:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Latest NPM.
          command: npm i -g npm@latest
      - run:
          name: NPM Install.
          command: npm i
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

  node8-latest:
    docker:
      - image: webpackcontrib/circleci-node8:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Latest NPM.
          command: npm i -g npm@latest
      - run:
          name: NPM Install.
          command: npm i
      - run:
          name: Run unit tests.
          command: npm run ci:coverage
      - run:
          name: Submit coverage data to codecov.
          command: bash <(curl -s https://codecov.io/bash)
          when: on_success
  node6-latest:
    docker:
      - image: webpackcontrib/circleci-node6:latest
    <<: *unit_tests
  node10-latest:
    docker:
      - image: webpackcontrib/circleci-node10:latest
    <<: *unit_tests
  node10-canary:
    docker:
      - image: webpackcontrib/circleci-node10:latest
    <<: *canary_tests
  analysis:
    docker:
      - image: webpackcontrib/circleci-node-base:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Latest NPM.
          command: npm i -g npm@latest
      - run:
          name: NPM Install.
          command: npm i
      - run:
          name: Run linting.
          command: npm run lint
      - run:
          name: Run NPM Audit.
          command: npm run security
      - run:
          name: Validate Commit Messages.
          command: npm run ci:lint:commits

workflows:
  version: 2
  validate-publish:
    jobs:
    - dependency_cache
    - node6-latest:
        requires:
          - dependency_cache
        filters:
          tags:
            only: /.*/
    - analysis:
        requires:
          - dependency_cache
        filters:
          tags:
            only: /.*/
    - node8-latest:
        requires:
          - analysis
          - node6-latest
        filters:
          tags:
            only: /.*/
    - node10-latest:
        requires:
          - analysis
          - node6-latest
        filters:
          tags:
            only: /.*/
    - node10-canary:
        requires:
          - analysis
          - node6-latest
        filters:
          tags:
            only: /.*/
